### ISSUE TITLE
testing new all-contributors app

### ISSUE THREAD

**Issue by gr2m** [gr2m/sandbox#163]

**Comment by gr2m** [comment]
@all-contributors please add @gr2m-test for infrastructure, tests and code

**Comment by gr2m** [comment]
@all-contributors please add @gr2m-test for infrastructure, tests and code

**Comment by gr2m** [comment]
@all-contributors please add @gr2m-test for code

**Comment by gr2m** [comment]
@all-contributors please add @gr2m-test for tests

**Comment by gr2m** [comment]
@all-contributors please add @gr2m-test for infrastructure

**Comment by gr2m** [comment]
@all-contributors please add @gr2m-test for infrastructure

**Comment by gr2m** [comment]
@all-contributors please add @gr2m-test for tests

**Comment by gr2m** [comment]
@all-contributors please add @gr2m for tests

**Comment by gr2m** [comment]
@all-contributors please add @Berkmann18 for mentoring

**Comment by Berkmann18** [comment]
@all-contributors please add @Berkmann18 for code

**Comment by gr2m** [comment]
the error was

```
TypeError: Cannot read property 'files' of undefined
    at Config.get (/var/task/lib/modules/config.js:73:32)
    at convertMessage (/var/task/lib/modules/convert-message.js:5:49)
    at Repository.updateFile (/var/task/lib/modules/repository.js:128:16)
    at Repository.createOrUpdateFile (/var/task/lib/modules/repository.js:153:18)
    at /var/task/lib/modules/repository.js:166:27
    at Array.map (<anonymous>)
    at Repository.createOrUpdateFiles (/var/task/lib/modules/repository.js:164:69)
    at Repository.createPullRequestFromFiles (/var/task/lib/modules/repository.js:236:16)
    at addContributor (/var/task/lib/add-contributor.js:51:24)
    at async processIssueComment (/var/task/lib/process-issue-comment.js:61:33)
```

**Comment by gr2m** [comment]
It should have been reported to sentry, the sentry event ID is `22c294492d3b4aaca6c44d1a8748cdcd`. But it's not showing up in the sentry.io app yet

**Comment by Berkmann18** [comment]
It may be taking time in showing up.
As for the error, I'll see if I can find a better solution whenever I'm free.

**Comment by gr2m** [comment]
I think it's the same error that you see in the tests here? https://github.com/all-contributors/app/pull/343/checks?check_run_id=1723922388#step:5:13

**Comment by Berkmann18** [comment]
That's true and it indeed seems that it only fails in the PR.

**Comment by Berkmann18** [comment]
@all-contributors please add @Berkmann18 for code

**Comment by Berkmann18** [comment]
Note (to self): check if the PR title is consistent with the commits when (the convention isn't Angular) if so the PR would be good to go.

**Comment by Berkmann18** [comment]
@all-contributors please add @gr2m for infra

**Comment by Berkmann18** [comment]
It seems like we need to have tests that read a mocked/dummy `.all-contributorsrc` and test when some of the values there differ. I'm not sure why there's an inconsistency in the PR above.

**Comment by gr2m** [comment]
looks like https://github.com/gr2m/sandbox/pull/167 was created by the @allcontributors app, not by @all-contributors-preview. Sorry, my fault. I installed the @allcontributors app all of my @gr2m repositories and forgot that I tested the preview here in this repo. 

How about we create a new organization @all-contributors-sandbox for dedicated testing?

**Comment by gr2m** [comment]
oh oh :D
